# Generated by Django 3.2.7 on 2021-12-04 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(default='tangutur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='lakkireddy223@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phonenumber',
            field=models.IntegerField(default=9739711764, verbose_name=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='rollno',
            field=models.IntegerField(default=223),
            preserve_default=False,
        ),
    ]
