# Generated by Django 3.2.7 on 2021-12-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0009_auto_20211204_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('rollno',)},
        ),
    ]
