# Generated by Django 3.2.7 on 2022-03-21 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0010_alter_student_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
