# Generated by Django 3.2.7 on 2022-05-28 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0012_student_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Studentt',
        ),
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Teacherr',
        ),
    ]
