# Generated by Django 3.2.7 on 2022-05-28 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0013_auto_20220528_1850'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studentt',
            new_name='std',
        ),
        migrations.RenameModel(
            old_name='Teacherr',
            new_name='tea',
        ),
    ]
